name: Firebase Deploy

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때마다 실행 (master로 쓰는 경우 변경)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3  # 소스코드를 받아오기

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # 혹은 18 등

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
